CREATE TABLE [dbo].[Users]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[Handle] NVARCHAR(100) NOT NULL,
	[Name] NVARCHAR(100) NOT NULL
)
GO

CREATE UNIQUE NONCLUSTERED INDEX [UK_Users_Id]
ON [dbo].[Users]
(
	[Id]
)
GO

CREATE UNIQUE NONCLUSTERED INDEX [UK_Users_Handle]
ON [dbo].[Users]
(
	[Handle]
)
GO